export const storeProducts = [
  {
  "author": "Virgil",
  "country": "Roman Empire",
  "img": "images/the-aeneid.jpg",
  "language": "Classical Latin",
  "link": "https://en.wikipedia.org/wiki/Aeneid\n",
  "pages": 442,
  "title": "The Aeneid",
  "year": 1923,
  "inCart": false,
    "count": 0,
    "total": 0,
    "id": 19,
    "price": 8
},
{
  "author": "Vyasa",
  "country": "India",
  "img": "images/the-mahab-harata.jpg",
  "language": "Sanskrit",
  "link": "https://en.wikipedia.org/wiki/Mahabharata\n",
  "pages": 276,
  "title": "Mahabharata",
  "year": 1700,
  "inCart": false,
    "count": 0,
    "total": 0,
    "id": 20,
    "price": 11
},
{
  "author": "Walt Whitman",
  "country": "United States",
  "img": "images/leaves-of-grass.jpg",
  "language": "English",
  "link": "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
  "pages": 152,
  "title": "Leaves of Grass",
  "year": 1855,
  "inCart": false,
    "count": 0,
    "total": 0,
    "id": 21,
    "price": 16
},
{
  "author": "Virginia Woolf",
  "country": "United Kingdom",
  "img": "images/mrs-dalloway.jpg",
  "language": "English",
  "link": "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
  "pages": 216,
  "title": "Mrs Dalloway",
  "year": 1925,
  "inCart": false,
    "count": 0,
    "total": 0,
    "id": 22,
    "price": 7
},
{
  "author": "Virginia Woolf",
  "country": "United Kingdom",
  "img": "images/to-the-lighthouse.jpg",
  "language": "English",
  "link": "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
  "pages": 209,
  "title": "To the Lighthouse",
  "year": 1927,
  "inCart": false,
    "count": 0,
    "total": 0,
    "id": 23,
    "price": 8
},
{
  "author": "Marguerite Yourcenar",
  "country": "France/Belgium",
  "img": "images/memoirs-of-hadrian.jpg",
  "language": "French",
  "link": "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
  "pages": 408,
  "title": "Memoirs of Hadrian",
  "year": 1951,
  "inCart": false,
    "count": 0,
    "total": 0,
    "id": 24,
    "price": 9
  },
  {
    "author": "Chinua Achebe",
    "country": "Nigeria",
    "img": "images/things-fall-apart.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    "pages": 209,
    "title": "Things Fall Apart",
    "year": 1958,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 1,
    "price": 22
  },
  {
    "author": "Hans Christian Andersen",
    "country": "Denmark",
    "img": "images/fairy-tales.jpg",
    "language": "Danish",
    "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    "pages": 784,
    "title": "Fairy tales",
    "year": 1836,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 2,
    "price": 12
  },
  {
    "author": "Dante Alighieri",
    "country": "Italy",
    "img": "images/the-divine-comedy.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    "pages": 928,
    "title": "The Divine Comedy",
    "year": 1315,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 3,
    "price": 6
  },
  {
    "author": "Jane Austen",
    "country": "United Kingdom",
    "img": "images/pride-and-prejudice.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "pages": 226,
    "title": "Pride and Prejudice",
    "year": 1813,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 4,
    "price": 12
  },
  {
    "author": "Honor\u00e9 de Balzac",
    "country": "France",
    "img": "images/le-pere-goriot.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    "pages": 443,
    "title": "Le P\u00e8re Goriot",
    "year": 1835,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 5,
    "price": 11
  },
  {
    "author": "Samuel Beckett",
    "country": "Republic of Ireland",
    "img": "images/molloy-malone-dies-the-unnamable.jpg",
    "language": "French, English",
    "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    "pages": 256,
    "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
    "year": 1952,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 6,
    "price": 0
  },
  {
    "author": "Giovanni Boccaccio",
    "country": "Italy",
    "img": "images/the-decameron.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/The_Decameron\n",
    "pages": 1024,
    "title": "The Decameron",
    "year": 1351,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 7,
    "price": 5
  },
  {
    "author": "Jorge Luis Borges",
    "country": "Argentina",
    "img": "images/ficciones.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Ficciones\n",
    "pages": 224,
    "title": "Ficciones",
    "year": 1965,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 8,
    "price": 13
  },
  {
    "author": "Emily Bront\u00eb",
    "country": "United Kingdom",
    "img": "images/wuthering-heights.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    "pages": 342,
    "title": "Wuthering Heights",
    "year": 1847,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 9,
    "price": 9
  },
  {
    "author": "Albert Camus",
    "country": "Algeria, French Empire",
    "img": "images/l-etranger.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    "pages": 185,
    "title": "The Stranger",
    "year": 1942,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 10,
    "price": 0
  },
  {
    "author": "Paul Celan",
    "country": "Romania, France",
    "img": "images/poems-paul-celan.jpg",
    "language": "German",
    "link": "\n",
    "pages": 320,
    "title": "Poems",
    "year": 1952,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 11,
    "price": 19
  },
  {
    "author": "Louis-Ferdinand C\u00e9line",
    "country": "France",
    "img": "images/voyage-au-bout-de-la-nuit.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    "pages": 505,
    "title": "Journey to the End of the Night",
    "year": 1932,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 12,
    "price": 10
  },
  {
    "author": "Miguel de Cervantes",
    "country": "Spain",
    "img": "images/don-quijote-de-la-mancha.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
    "pages": 1056,
    "title": "Don Quijote De La Mancha",
    "year": 1610,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 13,
    "price": 8
  },
  {
    "author": "Geoffrey Chaucer",
    "country": "England",
    "img": "images/the-canterbury-tales.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    "pages": 544,
    "title": "The Canterbury Tales",
    "year": 1450,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 14,
    "price": 7
  },
  {
    "author": "Anton Chekhov",
    "country": "Russia",
    "img": "images/stories-of-anton-chekhov.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    "pages": 194,
    "title": "Stories",
    "year": 1886,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 15,
    "price": 9
  },
  {
    "author": "Joseph Conrad",
    "country": "United Kingdom",
    "img": "images/nostromo.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Nostromo\n",
    "pages": 320,
    "title": "Nostromo",
    "year": 1904,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 16,
    "price": 11
  },
  {
    "author": "Charles Dickens",
    "country": "United Kingdom",
    "img": "images/great-expectations.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
    "pages": 194,
    "title": "Great Expectations",
    "year": 1861,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 17,
    "price": 9
  },
  {
    "author": "Denis Diderot",
    "country": "France",
    "img": "images/jacques-the-fatalist.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
    "pages": 596,
    "title": "Jacques the Fatalist",
    "year": 1796,
    "inCart": false,
    "count": 0,
    "total": 0,
    "id": 18,
    "price": 0
  }
]

export const detailProduct = {
  "author": "Denis Diderot",
  "country": "France",
  "img": "images/jacques-the-fatalist.jpg",
  "language": "French",
  "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
  "pages": 596,
  "title": "Jacques the Fatalist",
  "year": 1796,
  "inCart": false,
  "count": 0,
  "total": 0,
  "id": 18,
  "price": 0
};
